account/urls.py
from django.urls import path
from . import views
from account.views import ChangePasswordView


app_name = 'account'

urlpatterns = [
    path('register/', views.register_account, name='signupuser'),
    path('login/', views.login_account, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('profile/', views.profileuser, name='profileuser'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
]

blog/urls.py
from django.urls import path
from blog.views import PostsByCategory, PostsList, PostDetail

app_name = 'blog'

urlpatterns = [
    path('', PostsList.as_view(), name='blog'),
    path('<slug:slug>/', PostDetail.as_view(), name='post_detail'),
    path('category/<slug:slug>/', PostsByCategory.as_view(), name='category'),
] 

djstart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homeapp.urls')),
    path('account/', include('account.urls')),
    path('blog/', include('blog.urls', namespace="blog")),
]

if settings.DEBUG:
    
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)
    urlpatterns += (
            static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
            static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

homeapp/urls.py
from django.urls import path
from homeapp.views import show_home

app_name = 'homeapp'

urlpatterns = [
    path('', show_home, name='homepage'),
]

account/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse


class CategoryPost(models.Model):
    name_category = models.CharField(verbose_name='name category', max_length=90, db_index=True)
    slug = models.SlugField(verbose_name='slug', db_index=True, unique=True, null=True)
    content = models.TextField(verbose_name='content', blank=True)

    class Meta():
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self): 
        return self.name_category

    def get_absolute_url(self):
        return reverse('blog:category', kwargs={'slug': self.slug})
    


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='name post', db_index=True)
    slug = models.SlugField(verbose_name='slug', db_index=True, unique=True, null=True)
    content = models.TextField(verbose_name='text post')
    publish = models.BooleanField(default=True)
    datearticle = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(verbose_name='photo', upload_to='blog/', blank=True)
    category = models.ForeignKey(CategoryPost, verbose_name='category', on_delete=models.PROTECT, blank=True, null=True)

    class Meta:
        verbose_name = 'New post'
        verbose_name_plural = 'All posts'
 
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})
              

homeapp/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.models import User



class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email',)

account/views.py
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm
from django.contrib import messages

from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin



def register_account(request):
    if request.method == 'GET':
        return render(request, 'account/register_account.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:

                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('account:profileuser')
            except IntegrityError:
                return render(request, 'account/register_account.html',
                              {'form': UserCreationForm(), 'error': 'User already exists'})
        else:
            return render(request, 'account/register_account.html',
                          {'form': UserCreationForm(), 'error': 'Passwords do not match'})



def login_account(request):
    if request.method == 'GET':
        return render(request, 'account/login.html', {'form': AuthenticationForm()})
    else:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is None:
            return render(request, 'account/login.html',
                          {'form': AuthenticationForm(),
                           'error': 'User or password not defined. Register'})
        else:
            login(request, user)
            return redirect('account:profileuser')


@login_required
def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('homeapp:homepage')


 
@login_required
def profileuser(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, instance=request.user)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile has been updated!')
            return redirect('account:profileuser')
        else:
            return render(request, 'account/profileuser.html', {'profile_form': profile_form})    
    else:
        profile_form = ProfileForm()
        return render(request, 'account/profileuser.html', {'profile_form': profile_form})


class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'account/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('account:profileuser')        

blog/views.py
# from django.shortcuts import render, get_object_or_404
from .models import Blog, CategoryPost
from django.views.generic import ListView, DetailView


class PostsList(ListView):
    model = Blog
    template_name = "blog/blog_list.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['allcategories'] = CategoryPost.objects.all()
        context['category_selected'] = 0
        return context
    
    def get_queryset(self):
        return Blog.objects.filter(publish=True)


class PostDetail(DetailView):
    model = Blog
    template_name = 'blog/showpost.html'
    context_object_name = 'detail_post'


class PostsByCategory(ListView):
    model = CategoryPost
    template_name = "blog/blog_list.html"
    # allow_empty = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['allcategories'] = CategoryPost.objects.all()
        return context

    def get_queryset(self):
        return Blog.objects.filter(category__slug=self.kwargs['slug'], publish=True)

homeapp/views.py
from django.shortcuts import render

def show_home(request):
    return render(request, 'homeapp/home.html')

blog/templates/blog/blog_list.html
{% extends 'base.html' %}
{% block title %} My blog {% endblock title %}
 {% block content %}

<div class="container-fluid py-5">
<h1 class="text-center mb-5">My blog</h1>

      <div class="row">
        <div class="col-md-3 col-sm-12 col-xs-12">
 {% comment %} <div class="sidebar">
      <div class="list-group py-3">
        {% if category_selected == 0 %}
        <h5 class="text-center">All posts</h5>
        {% else %}
        <a href="{% url 'blog:blog' %}" class="list-group-item list-group-item-action" aria-current="true">All posts</a>
        {% endif %}
      
        {% for item in allcategories %}
       <div class="link_category">
          <a href="{{ item.get_absolute_url }}" class="list-group-item list-group-item-action" aria-current="true">{{ item.name_category }}</a>
       </div>
       {% endfor %} 
      </div>
</div>   {% endcomment %}

{% include '_inc/_sidebar.html' %}
        </div>
        <div class="col-md-9 col-sm-12 col-xs-12">
          <div class="row">
            
        {% if object_list %}
        {% for post in object_list %}
       <div class="col-md-4 col-sm-6 col-xs-12">
         <div class="card shadow rounded">
           <div class="card-body">
             <h5 class="card-title text-center mb-3">{{ post.title }}</h5>
             <hr>
         <div class="link_category text-center mb-3">
           Category: <a href="{{ post.category.get_absolute_url }}" class=""> {{ post.category }}</a>
         </div>
            
             {% if post.photo %}
             <div class="photo mb-3">
               <img
                 src="{{ post.photo.url }}"
                 alt="{{ post.title }}"
                 style="width: 100%"
               />
             </div>
             {% else %}
             <img
               src="https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?cs=srgb&dl=pexels-luis-gomes-546819.jpg&fm=jpg"
               alt="{{ post.title }}"
               style="width: 100%"
               class="mb-3"
             />
             {% endif %}
             <a href="{{ post.get_absolute_url }}" class="card-link">Read more</a>
           </div>
         </div>
       </div>
        {% endfor %}

       {% else %}
       <h4>no posts</h4>
       {% endif %}
          </div>
        </div>
      </div>
</div>
{% endblock content %}

blog/templates/blog/show_sidebar.html
<div class="sidebar">
    <div class="list-group shadow rounded">
  <a href="{% url 'blog:blog' %}" class="list-group-item list-group-item-action" aria-current="true">All posts</a>
       {% for item in categories %}
     <div class="link_category">
        <a href="{{ item.get_absolute_url }}" class="list-group-item list-group-item-action" aria-current="true">{{ item.name_category }}</a>
     </div>
     {% endfor %} 
    </div>
</div> 

blog/templates/blog/showpost.html
{% extends 'base.html' %}
{% block title %}
{{ detail_post.title }}
{% endblock title %}
{% block content %}
<div class="container py-5">
<h1>{{ detail_post.title }}</h1>
<p class="badge bg-success">Category: {{ detail_post.category }}</p>
<hr>
{% if detail_post.photo %}
<div class="photo mb-3">
    <img src="{{ detail_post.photo.url }}" alt="{{ detail_post.title }}" style="width:250px;">
</div>
{% else %}
<img src="https://images.pexels.com/photos/546819/pexels-photo-546819.jpeg?cs=srgb&dl=pexels-luis-gomes-546819.jpg&fm=jpg" alt="{{ post.title }}" style="width:250px;">
{% endif %}
<hr>
<div class="content">
    {{ detail_post.content }}
</div>
</div>
{% endblock content %}

homeapp/templates/homeapp/home.html
{% extends 'base.html' %}
{% block title %}
Homepage
{% endblock title %}
{% block content %}
<div class="container">
<h1 class="py-3">Homepage</h1>
<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rem fugiat ipsum deleniti, saepe necessitatibus dicta est officiis temporibus, consequuntur illo quos. Exercitationem asperiores eum illo molestiae nobis quis iure itaque!
Maxime, deserunt accusamus sit amet aliquid vitae dolorum delectus obcaecati totam, architecto praesentium, laboriosam cum debitis. Debitis necessitatibus assumenda quam consectetur laborum quibusdam molestiae, at nisi, sint fugit non cupiditate.
Veniam sunt consequatur libero! Eaque consectetur eos dolorum quos deleniti amet. Magnam architecto dignissimos nobis ut, provident, voluptas ducimus earum nam rerum fugiat expedita! Nihil sit quaerat non provident aliquid.
Rerum cumque possimus sapiente illo qui earum corporis, libero, aspernatur ipsa iure aliquid eos praesentium doloribus dolores? Rerum non dolores officia quis enim tenetur iure voluptatum nisi voluptatibus. Voluptate, sint!
Modi hic nostrum voluptate doloribus consequatur esse facilis ullam molestias, voluptatum blanditiis rem libero iusto ipsa et quod itaque! Placeat minima blanditiis error repudiandae qui dicta esse consectetur commodi fugit.</p>
<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rem fugiat ipsum deleniti, saepe necessitatibus dicta est officiis temporibus, consequuntur illo quos. Exercitationem asperiores eum illo molestiae nobis quis iure itaque!
    Maxime, deserunt accusamus sit amet aliquid vitae dolorum delectus obcaecati totam, architecto praesentium, laboriosam cum debitis. Debitis necessitatibus assumenda quam consectetur laborum quibusdam molestiae, at nisi, sint fugit non cupiditate.
    Veniam sunt consequatur libero! Eaque consectetur eos dolorum quos deleniti amet. Magnam architecto dignissimos nobis ut, provident, voluptas ducimus earum nam rerum fugiat expedita! Nihil sit quaerat non provident aliquid.
    Rerum cumque possimus sapiente illo qui earum corporis, libero, aspernatur ipsa iure aliquid eos praesentium doloribus dolores? Rerum non dolores officia quis enim tenetur iure voluptatum nisi voluptatibus. Voluptate, sint!
    Modi hic nostrum voluptate doloribus consequatur esse facilis ullam molestias, voluptatum blanditiis rem libero iusto ipsa et quod itaque! Placeat minima blanditiis error repudiandae qui dicta esse consectetur commodi fugit.</p>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rem fugiat ipsum deleniti, saepe necessitatibus dicta est officiis temporibus, consequuntur illo quos. Exercitationem asperiores eum illo molestiae nobis quis iure itaque!
        Maxime, deserunt accusamus sit amet aliquid vitae dolorum delectus obcaecati totam, architecto praesentium, laboriosam cum debitis. Debitis necessitatibus assumenda quam consectetur laborum quibusdam molestiae, at nisi, sint fugit non cupiditate.
        Veniam sunt consequatur libero! Eaque consectetur eos dolorum quos deleniti amet. Magnam architecto dignissimos nobis ut, provident, voluptas ducimus earum nam rerum fugiat expedita! Nihil sit quaerat non provident aliquid.
        Rerum cumque possimus sapiente illo qui earum corporis, libero, aspernatur ipsa iure aliquid eos praesentium doloribus dolores? Rerum non dolores officia quis enim tenetur iure voluptatum nisi voluptatibus. Voluptate, sint!
        Modi hic nostrum voluptate doloribus consequatur esse facilis ullam molestias, voluptatum blanditiis rem libero iusto ipsa et quod itaque! Placeat minima blanditiis error repudiandae qui dicta esse consectetur commodi fugit.</p>
</div>
{% endblock content %}

templates/_inc/_footer.html
<footer class="py-5">
<div class="container">
  <h3 class="text-center">&#169; TitleCompany, 2022</h3>
</div> 
</footer>

templates/_inc/_header.html
<header>
  <div class="container">
    <div class="d-flex justify-content-end">
 {% if user.is_authenticated %}
     <form action="{% url 'account:logoutuser' %}" method="post" class="py-3">
    {% csrf_token %}
    <span class="badge rounded-pill bg-success fs-5">Hello {{ user.username }}</span> <button type="submit" class="badge rounded-pill bg-danger fs-6">Logout</button>
  </form>
{% endif %}
   </div> 
  </div>
</header>

templates/_inc/_menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
  <div class="container d-flex flex-wrap">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="nav me-auto">
      <li class="nav-item"><a href="{% url 'homeapp:homepage' %}" class="nav-link link-dark px-2 active" aria-current="page">Home</a></li>
      <li class="nav-item"><a href="{% url 'blog:blog' %}" class="nav-link link-dark px-2">Blog</a></li>
    </ul>
    {% if user.is_authenticated %}
    <ul class="nav">
      <li class="nav-item"><a href="{% url 'account:profileuser' %}" class="nav-link link-dark px-2">Profile</a></li>
      {% if user.is_superuser %}
      <li class="nav-item"><a href="{% url 'admin:index' %}" class="nav-link link-dark px-2">Admin</a></li>
      {% endif %}
    </ul>
    {% else %}
    <ul class="nav">
      <li class="nav-item"><a href="{% url 'account:loginuser' %}" class="nav-link link-dark px-2">Login</a></li>
      <li class="nav-item"><a href="{% url 'account:signupuser' %}" class="nav-link link-dark px-2">Sign up</a></li>
    </ul>
    {% endif %}

  </div>
  </div>
</nav>

templates/_inc/_sidebar.html
{% load show_sidebar %}

{% show_categories %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
          <link rel="stylesheet" href="{% static 'homeapp/app.css' %}">
    <title>
        {% block title %}

        {% endblock title %}
    </title>
</head>
<body>
{% include '_inc/_header.html' %}
{% include '_inc/_menu.html' %}

{% block content %}

{% endblock content %}
{% include '_inc/_footer.html' %}
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
        <script src="{% static 'homeapp/app.js' %}"></script>
</body>
</html>